In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv("edited_rating.csv")

In [62]:
df.shape

(20000263, 4)

In [63]:
num_users = df["userId"].max()
num_movies = df["movie_idx"].max()
print("users", num_users, "movies", num_movies)

users 138492 movies 26743

In [1]:
df.head(10)

NameError: name 'df' is not defined

In [65]:
num_of_users = 5000
num_of_movies = 1000
user_filter = df['userId'].value_counts()[:num_of_users].index.tolist()
movie_filter = df['movie_idx'].value_counts()[:num_of_movies].index.tolist()

In [66]:
df_small= df[df["userId"].isin(user_filter) & df["movie_idx"].isin(movie_filter)].copy()

In [67]:
df_small.head()

      userId  movieId  rating  movie_idx
5400      53        1     4.0          1
5401      53        2     3.0          2
5402      53        5     3.0          5
5403      53        6     3.0          6
5404      53       10     4.0         10

In [68]:
user_ids = set(df_small.userId.values)
movie_ids= set(df_small.movie_idx.values)
new_user_id_map = {}
new_movie_id_map = {}
i=0
j=0
for old in user_ids:
  new_user_id_map[old] = i
  i+=1

for old in movie_ids:
  new_movie_id_map[old] = j
  j += 1

In [78]:
new_user_id_map

{65541: 0,
 32779: 1,
 131085: 2,
 131099: 3,
 53: 4,
 57: 5,
 98393: 6,
 90: 7,
 98394: 8,
 32860: 9,
 98400: 10,
 103: 11,
 65643: 12,
 131179: 13,
 32880: 14,
 115: 15,
 98419: 16,
 65665: 17,
 32898: 18,
 131203: 19,
 65669: 20,
 32905: 21,
 65686: 22,
 131226: 23,
 155: 24,
 65693: 25,
 98463: 26,
 98469: 27,
 65717: 28,
 98486: 29,
 98490: 30,
 131260: 31,
 98493: 32,
 131274: 33,
 131276: 34,
 131278: 35,
 207: 36,
 32983: 37,
 65758: 38,
 98527: 39,
 98540: 40,
 65776: 41,
 65784: 42,
 131332: 43,
 33034: 44,
 131346: 45,
 33051: 46,
 98596: 47,
 293: 48,
 297: 49,
 33081: 50,
 65851: 51,
 131394: 52,
 33091: 53,
 131406: 54,
 346: 55,
 347: 56,
 358: 57,
 131433: 58,
 366: 59,
 33135: 60,
 369: 61,
 65918: 62,
 98686: 63,
 387: 64,
 98695: 65,
 393: 66,
 131466: 67,
 131483: 68,
 412: 69,
 33181: 70,
 33184: 71,
 33189: 72,
 65958: 73,
 423: 74,
 98728: 75,
 33204: 76,
 33208: 77,
 131530: 78,
 98780: 79,
 66022: 80,
 66040: 81,
 98811: 82,
 66048: 83,
 131584: 84,
 131587: 85,
 131619: 86,
 33318: 87,
 66087: 88,
 33322: 89,
 131629: 90,
 98864: 91,
 98870: 92,
 98874: 93,
 571: 94,
 66114: 95,
 131650: 96,
 33348: 97,
 585: 98,
 586: 99,
 33356: 100,
 98908: 101,
 66142: 102,
 33375: 103,
 613: 104,
 33383: 105,
 98920: 106,
 131697: 107,
 630: 108,
 631: 109,
 33401: 110,
 636: 111,
 66178: 112,
 66179: 113,
 647: 114,
 131720: 115,
 66200: 116,
 131745: 117,
 66225: 118,
 98998: 119,
 701: 120,
 66240: 121,
 66242: 122,
 709: 123,
 716: 124,
 33494: 125,
 66262: 126,
 99039: 127,
 740: 128,
 131828: 129,
 131835: 130,
 767: 131,
 66304: 132,
 774: 133,
 99078: 134,
 776: 135,
 66316: 136,
 66324: 137,
 99102: 138,
 66337: 139,
 33574: 140,
 811: 141,
 33580: 142,
 99118: 143,
 33586: 144,
 131893: 145,
 131895: 146,
 66361: 147,
 131903: 148,
 131908: 149,
 131909: 150,
 99155: 151,
 855: 152,
 33623: 153,
 99163: 154,
 131933: 155,
 66400: 156,
 99170: 157,
 99174: 158,
 131960: 159,
 131964: 160,
 902: 161,
 99207: 162,
 909: 163,
 33689: 164,
 33712: 165,
 66481: 166,
 954: 167,
 33728: 168,
 66498: 169,
 132038: 170,
 33735: 171,
 970: 172,
 99275: 173,
 132049: 174,
 981: 175,
 66532: 176,
 132072: 177,
 99312: 178,
 132081: 179,
 1010: 180,
 132089: 181,
 132094: 182,
 33802: 183,
 99341: 184,
 99346: 185,
 33817: 186,
 1051: 187,
 99359: 188,
 132135: 189,
 33832: 190,
 99370: 191,
 33840: 192,
 132145: 193,
 66616: 194,
 99385: 195,
 66634: 196,
 1112: 197,
 66648: 198,
 132184: 199,
 132186: 200,
 132194: 201,
 99430: 202,
 132209: 203,
 99447: 204,
 99457: 205,
 1164: 206,
 99473: 207,
 99484: 208,
 66718: 209,
 1184: 210,
 99498: 211,
 1199: 212,
 66740: 213,
 33973: 214,
 33980: 215,
 99517: 216,
 33984: 217,
 99521: 218,
 99522: 219,
 99523: 220,
 99524: 221,
 66762: 222,
 132309: 223,
 1243: 224,
 99548: 225,
 99551: 226,
 132320: 227,
 132330: 228,
 66809: 229,
 66812: 230,
 66818: 231,
 66824: 232,
 66826: 233,
 34061: 234,
 1295: 235,
 34066: 236,
 66835: 237,
 66836: 238,
 132385: 239,
 132391: 240,
 132392: 241,
 1322: 242,
 132402: 243,
 34102: 244,
 132414: 245,
 34123: 246,
 34126: 247,
 66897: 248,
 34139: 249,
 34142: 250,
 34155: 251,
 66928: 252,
 132465: 253,
 99710: 254,
 1410: 255,
 34178: 256,
 34179: 257,
 66951: 258,
 1418: 259,
 34186: 260,
 1420: 261,
 34190: 262,
 99733: 263,
 66966: 264,
 34201: 265,
 132508: 266,
 34206: 267,
 99753: 268,
 34223: 269,
 99772: 270,
 99780: 271,
 67021: 272,
 34261: 273,
 1506: 274,
 132583: 275,
 132585: 276,
 1515: 277,
 67052: 278,
 132598: 279,
 132602: 280,
 132605: 281,
 67074: 282,
 34312: 283,
 99854: 284,
 132628: 285,
 1559: 286,
 34333: 287,
 99870: 288,
 132638: 289,
 132642: 290,
 67112: 291,
 67116: 292,
 34349: 293,
 1587: 294,
 132666: 295,
 1601: 296,
 34381: 297,
 99929: 298,
 34394: 299,
 99936: 300,
 34401: 301,
 99940: 302,
 34408: 303,
 1643: 304,
 67180: 305,
 67184: 306,
 34418: 307,
 132725: 308,
 34439: 309,
 132746: 310,
 1677: 311,
 99984: 312,
 34451: 313,
 67223: 314,
 1714: 315,
 67251: 316,
 34484: 317,
 100019: 318,
 100022: 319,
 132788: 320,
 34493: 321,
 1728: 322,
 67266: 323,
 34503: 324,
 1740: 325,
 34510: 326,
 67282: 327,
 1747: 328,
 1754: 329,
 132827: 330,
 1762: 331,
 67302: 332,
 132845: 333,
 67324: 334,
 67339: 335,
 34575: 336,
 67345: 337,
 132881: 338,
 132883: 339,
 34583: 340,
 67351: 341,
 34586: 342,
 100133: 343,
 34600: 344,
 1848: 345,
 67386: 346,
 34619: 347,
 1853: 348,
 1863: 349,
 34631: 350,
 100168: 351,
 34636: 352,
 132946: 353,
 34649: 354,
 34650: 355,
 1886: 356,
 34655: 357,
 132972: 358,
 34669: 359,
 1905: 360,
 67442: 361,
 1907: 362,
 100212: 363,
 100213: 364,
 34682: 365,
 1930: 366,
 34699: 367,
 67476: 368,
 1941: 369,
 133017: 370,
 100253: 371,
 1965: 372,
 100272: 373,
 1971: 374,
 67517: 375,
 100285: 376,
 34757: 377,
 67526: 378,
 133071: 379,
 34769: 380,
 67543: 381,
 67545: 382,
 133088: 383,
 2023: 384,
 67562: 385,
 67568: 386,
 2037: 387,
 100348: 388,
 67586: 389,
 100357: 390,
 34822: 391,
 34825: 392,
 133132: 393,
 100365: 394,
 100366: 395,
 100368: 396,
 100370: 397,
 67603: 398,
 100372: 399,
 2071: 400,
 67608: 401,
 34855: 402,
 2098: 403,
 2112: 404,
 100417: 405,
 133186: 406,
 67656: 407,
 67657: 408,
 67665: 409,
 34898: 410,
 100437: 411,
 133213: 412,
 2157: 413,
 100463: 414,
 2160: 415,
 67697: 416,
 100470: 417,
 2170: 418,
 67708: 419,
 34953: 420,
 100491: 421,
 100505: 422,
 34970: 423,
 133291: 424,
 34994: 425,
 34998: 426,
 2231: 427,
 35003: 428,
 133308: 429,
 133309: 430,
 35010: 431,
 100555: 432,
 133323: 433,
 35021: 434,
 133328: 435,
 2260: 436,
 35036: 437,
 35049: 438,
 67824: 439,
 100595: 440,
 133364: 441,
 67829: 442,
 35065: 443,
 133371: 444,
 67838: 445,
 100613: 446,
 2310: 447,
 35090: 448,
 35097: 449,
 100638: 450,
 133409: 451,
 35108: 452,
 2343: 453,
 67880: 454,
 35114: 455,
 100651: 456,
 2348: 457,
 2351: 458,
 35120: 459,
 35127: 460,
 100668: 461,
 2373: 462,
 2377: 463,
 100696: 464,
 2396: 465,
 2397: 466,
 133474: 467,
 100711: 468,
 100712: 469,
 35178: 470,
 35189: 471,
 67960: 472,
 100737: 473,
 67978: 474,
 67984: 475,
 35226: 476,
 67995: 477,
 100765: 478,
 100780: 479,
 35250: 480,
 2483: 481,
 100790: 482,
 35257: 483,
 68025: 484,
 100800: 485,
 100803: 486,
 100804: 487,
 35281: 488,
 2516: 489,
 68059: 490,
 68062: 491,
 2567: 492,
 35351: 493,
 35355: 494,
 133683: 495,
 68160: 496,
 133696: 497,
 133699: 498,
 68166: 499,
 133702: 500,
 100937: 501,
 68179: 502,
 35414: 503,
 68182: 504,
 100952: 505,
 2649: 506,
 35423: 507,
 2656: 508,
 100968: 509,
 2668: 510,
 35438: 511,
 68213: 512,
 68214: 513,
 100991: 514,
 35459: 515,
 68232: 516,
 2710: 517,
 68249: 518,
 2717: 519,
 68259: 520,
 2731: 521,
 133810: 522,
 101043: 523,
 35509: 524,
 35513: 525,
 133820: 526,
 133824: 527,
 35521: 528,
 2756: 529,
 68292: 530,
 2761: 531,
 35537: 532,
 2771: 533,
 133871: 534,
 68340: 535,
 101109: 536,
 68350: 537,
 68357: 538,
 101126: 539,
 35600: 540,
 101139: 541,
 35608: 542,
 101145: 543,
 2842: 544,
 101154: 545,
 133924: 546,
 101164: 547,
 35630: 548,
 2865: 549,
 101170: 550,
 133949: 551,
 68414: 552,
 2914: 553,
 133999: 554,
 2929: 555,
 101233: 556,
 35704: 557,
 101241: 558,
 35708: 559,
 2944: 560,
 68496: 561,
 134037: 562,
 101273: 563,
 68506: 564,
 101274: 565,
 101281: 566,
 2987: 567,
 35760: 568,
 134079: 569,
 35779: 570,
 68557: 571,
 3028: 572,
 35803: 573,
 68574: 574,
 101344: 575,
 134125: 576,
 35833: 577,
 134137: 578,
 101371: 579,
 101372: 580,
 134143: 581,
 134155: 582,
 134158: 583,
 134174: 584,
 68642: 585,
 134180: 586,
 101419: 587,
 134209: 588,
 134214: 589,
 101451: 590,
 101457: 591,
 134232: 592,
 3170: 593,
 68709: 594,
 35944: 595,
 3183: 596,
 3196: 597,
 101504: 598,
 3206: 599,
 68743: 600,
 101514: 601,
 35984: 602,
 3217: 603,
 134289: 604,
 68758: 605,
 134298: 606,
 35996: 607,
 36001: 608,
 36002: 609,
 36016: 610,
 3250: 611,
 134322: 612,
 134327: 613,
 3256: 614,
 68795: 615,
 3267: 616,
 3268: 617,
 101576: 618,
 36047: 619,
 134351: 620,
 68817: 621,
 3283: 622,
 3288: 623,
 101610: 624,
 36081: 625,
 3317: 626,
 36092: 627,
 134400: 628,
 36097: 629,
 36098: 630,
 68868: 631,
 101651: 632,
 68891: 633,
 101674: 634,
 68912: 635,
 101695: 636,
 3396: 637,
 101702: 638,
 68960: 639,
 134496: 640,
 134498: 641,
 36203: 642,
 3449: 643,
 36220: 644,
 36224: 645,
 134534: 646,
 101767: 647,
 134537: 648,
 101784: 649,
 3486: 650,
 36262: 651,
 134566: 652,
 69039: 653,
 3512: 654,
 3513: 655,
 3514: 656,
 134592: 657,
 36290: 658,
 36307: 659,
 36309: 660,
 36311: 661,
 36312: 662,
 69079: 663,
 69081: 664,
 101860: 665,
 36328: 666,
 134636: 667,
 3570: 668,
 3575: 669,
 134652: 670,
 134656: 671,
 69123: 672,
 3591: 673,
 101903: 674,
 134675: 675,
 69147: 676,
 3617: 677,
 134689: 678,
 36390: 679,
 3624: 680,
 36393: 681,
 3628: 682,
 101947: 683,
 134727: 684,
 101962: 685,
 3659: 686,
 3663: 687,
 101967: 688,
 101974: 689,
 3672: 690,
 3675: 691,
 69211: 692,
 102000: 693,
 102003: 694,
 134772: 695,
 134773: 696,
 3703: 697,
 134781: 698,
 36480: 699,
 36481: 700,
 102024: 701,
 102037: 702,
 3742: 703,
 3745: 704,
 69281: 705,
 102054: 706,
 102055: 707,
 69290: 708,
 69303: 709,
 134856: 710,
 134858: 711,
 102097: 712,
 134865: 713,
 3796: 714,
 102117: 715,
 36593: 716,
 102130: 717,
 134904: 718,
 134910: 719,
 69377: 720,
 102158: 721,
 134928: 722,
 3857: 723,
 3863: 724,
 134951: 725,
 69425: 726,
 102195: 727,
 102196: 728,
 134976: 729,
 3906: 730,
 36680: 731,
 3926: 732,
 69472: 733,
 135014: 734,
 69480: 735,
 3947: 736,
 102251: 737,
 102254: 738,
 69493: 739,
 102261: 740,
 69495: 741,
 135032: 742,
 3970: 743,
 102278: 744,
 36744: 745,
 3989: 746,
 135070: 747,
 69537: 748,
 135074: 749,
 135081: 750,
 135089: 751,
 135091: 752,
 69560: 753,
 135096: 754,
 135104: 755,
 102341: 756,
 69576: 757,
 102348: 758,
 36820: 759,
 69595: 760,
 4065: 761,
 102372: 762,
 135154: 763,
 4083: 764,
 4086: 765,
 4088: 766,
 36868: 767,
 69644: 768,
 135180: 769,
 135182: 770,
 135185: 771,
 69653: 772,
 135193: 773,
 135195: 774,
 69661: 775,
 69663: 776,
 4128: 777,
 102439: 778,
 102441: 779,
 69682: 780,
 4149: 781,
 135231: 782,
 69698: 783,
 69701: 784,
 102496: 785,
 4216: 786,
 36984: 787,
 69752: 788,
 4221: 789,
 102531: 790,
 69792: 791,
 102564: 792,
 135342: 793,
 37041: 794,
 4275: 795,
 37050: 796,
 69819: 797,
 4284: 798,
 37052: 799,
 69828: 800,
 4294: 801,
 102598: 802,
 135369: 803,
 37071: 804,
 37073: 805,
 4307: 806,
 69849: 807,
 135387: 808,
 135396: 809,
 135398: 810,
 69867: 811,
 102645: 812,
 135417: 813,
 4346: 814,
 135424: 815,
 4357: 816,
 102679: 817,
 37144: 818,
 69915: 819,
 102685: 820,
 4388: 821,
 37160: 822,
 69933: 823,
 102704: 824,
 102713: 825,
 102724: 826,
 4422: 827,
 37191: 828,
 69961: 829,
 4427: 830,
 135504: 831,
 102742: 832,
 135518: 833,
 37216: 834,
 4449: 835,
 135521: 836,
 69987: 837,
 102763: 838,
 135534: 839,
 135549: 840,
 37249: 841,
 37252: 842,
 70024: 843,
 37263: 844,
 4499: 845,
 4506: 846,
 135594: 847,
 37293: 848,
 4528: 849,
 4530: 850,
 70067: 851,
 70072: 852,
 102844: 853,
 37316: 854,
 102852: 855,
 37318: 856,
 102864: 857,
 37330: 858,
 37332: 859,
 37351: 860,
 102887: 861,
 37353: 862,
 4586: 863,
 4593: 864,
 4597: 865,
 4599: 866,
 70140: 867,
 102910: 868,
 135693: 869,
 37412: 870,
 102953: 871,
 37421: 872,
 37422: 873,
 70200: 874,
 70212: 875,
 135752: 876,
 135764: 877,
 4695: 878,
 70231: 879,
 70242: 880,
 103017: 881,
 103026: 882,
 103027: 883,
 135794: 884,
 135805: 885,
 135807: 886,
 4744: 887,
 70281: 888,
 135818: 889,
 4747: 890,
 135827: 891,
 4758: 892,
 4759: 893,
 37529: 894,
 70302: 895,
 103075: 896,
 103077: 897,
 37546: 898,
 103087: 899,
 103089: 900,
 103108: 901,
 70341: 902,
 37576: 903,
 70345: 904,
 103112: 905,
 70349: 906,
 135887: 907,
 37584: 908,
 4821: 909,
 103125: 910,
 4830: 911,
 103135: 912,
 70378: 913,
 70385: 914,
 4854: 915,
 37622: 916,
 70390: 917,
 103180: 918,
 4883: 919,
 103194: 920,
 103198: 921,
 103202: 922,
 135975: 923,
 70445: 924,
 135983: 925,
 4913: 926,
 70452: 927,
 103222: 928,
 135992: 929,
 4923: 930,
 37694: 931,
 4936: 932,
 136014: 933,
 103253: 934,
 4964: 935,
 4966: 936,
 4967: 937,
 70508: 938,
 136052: 939,
 136053: 940,
 37753: 941,
 103290: 942,
 103293: 943,
 37763: 944,
 103305: 945,
 136081: 946,
 37779: 947,
 103328: 948,
 5035: 949,
 70575: 950,
 37813: 951,
 37822: 952,
 37824: 953,
 103361: 954,
 5062: 955,
 37841: 956,
 5083: 957,
 37858: 958,
 5101: 959,
 5106: 960,
 37889: 961,
 70662: 962,
 37896: 963,
 5136: 964,
 5137: 965,
 37913: 966,
 136222: 967,
 5154: 968,
 5156: 969,
 37924: 970,
 103469: 971,
 70720: 972,
 103491: 973,
 136261: 974,
 5194: 975,
 136267: 976,
 70739: 977,
 5215: 978,
 70751: 979,
 103520: 980,
 136292: 981,
 37990: 982,
 103527: 983,
 136300: 984,
 37998: 985,
 70769: 986,
 70815: 987,
 5302: 988,
 5313: 989,
 38081: 990,
 70853: 991,
 70870: 992,
 103640: 993,
 70876: 994,
 70882: 995,
 103653: 996,
 38118: 997,
 5351: 998,
 70888: 999,
 ...}

In [72]:
df_small.head()

      userId  movieId  rating  movie_idx
5400      53        1     4.0          1
5401      53        2     3.0          2
5402      53        5     3.0          5
5403      53        6     3.0          6
5404      53       10     4.0         10

In [76]:
df_small['new_userId'] = df["userId"].map(new_user_id_map)
df_small['new_movieId'] = df["movie_idx"].map(new_movie_id_map)

In [80]:
df_small.tail(10)

          userId  movieId  rating  movie_idx  new_userId  new_movieId
19993352  138436    69122     4.0      13842      1354.0        808.0
19993354  138436    69757     4.5      13968      1354.0        857.0
19993355  138436    70286     5.0      14060      1354.0        881.0
19993357  138436    71535     4.0      14329      1354.0        997.0
19993360  138436    72998     3.5      14640      1354.0        207.0
19993363  138436    74458     3.5      14917      1354.0        721.0
19993369  138436    78499     4.0      15448      1354.0        584.0
19993372  138436    79132     4.5      15580      1354.0        678.0
19993375  138436    80463     4.0      15901      1354.0        817.0
19993378  138436    81591     4.0      16168      1354.0        909.0

In [82]:
print("max user id:", df_small.new_userId.max())
print("max movie id:", df_small.new_movieId.max())

print("small dataframe size:", len(df_small))

max user id: 4999.0
max movie id: 999.0
small dataframe size: 2353634

In [83]:
df_small.to_csv('small_rating.csv', index=False)

In [ ]:
rating_mat = df.pivot(index="userId", columns="movieId", values ="rating")